
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 18 15:41:03 CET 2013
//----------------------------------------------------

package com.dev.campus.analyser;

/** CUP generated class containing symbol constants. */
public class MySymbol {
  /* terminals */
  public static final int AT = 2;
  public static final int TIME = 4;
  public static final int error = 1;
  public static final int FROM = 3;
  public static final int EOF = 0;
}

